run:
  name: development_celltypist
  mode: development

datasets:
  healthy:
    - aidav2
    - immuneindonesia
    - immunobiologyaging
    - onek1k
    - terekhova
  validation: []
  query: []

sampling:
  max_donors_per_dataset: 3
  max_cells_per_donor: 100
  sampler_modes: [hybrid]

models:
  tripso:
    enabled: true
    epochs: 5
    seeds:
      - 1

reports:
  generate_full_report: false
